### ISSUE TITLE
Extract css into a separate file

### ISSUE THREAD

**Issue by cristijora** [euvl/vue-js-grid#6]
From what I see, the css is bundled together inside the final js output.
This can be an issue if you want to customize the css later on.
Also there is some css directly on the body 
https://github.com/euvl/vue-js-grid/blob/master/src/Grid.vue#L228

**Comment by euvl** [comment]
Hey @cristijora,

Good point, and the body part should clearly go away, thanks.
I am not sure though how to include extracted css when the user calls `Vue.use(Grid)` (or how is it done with extracted css?).

Do you have any thought on how it can be done?

**Comment by cristijora** [comment]
It can't be included in `Vue.use(Grid)`
The installation would rather be
```js
import 'vue-js-grid/dist/grid.css'
import Grid from 'vue-js-grid'
Vue.use(Grid)
```

**Comment by euvl** [comment]
Hm, you see, the css in the plugin is crucial for plugin to work. It contains bare minimum and hopefully never will be changed beyond the changes allowed by plugin's props.

I feel like plonking it into separate file does not bring any positive effects and only might add more confusion (user's might expect the css file to be a feature rather than a requirement).

**Comment by euvl** [comment]
It actually was a good call to remove body class, i've found a bug in position calculation function 😄 👍

**Comment by cristijora** [comment]
Understood your point here. Closing the issue as this is not in scope. Thanks for removing the body class
